// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/bs-jest/src/jest.js";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";
import * as Component2$ReactTemplate from "../src/Component2.bs.js";

describe("Basic", (function () {
        Jest.test("mod", (function () {
                return Jest.Expect[/* toBe */2](3, Jest.Expect[/* expect */0](3));
              }));
        return Jest.test("will fail", (function () {
                      return Jest.Expect[/* toBe */2](3, Jest.Expect[/* expect */0](77));
                    }));
      }));

describe("Component2", (function () {
        Jest.test("getMode Hanzi", (function () {
                return Jest.Expect[/* toBe */2](/* Hanzi */894130468, Jest.Expect[/* expect */0](Component2$ReactTemplate.getMode(/* Hanzi */894130468)));
              }));
        Jest.test("getMode Emoji", (function () {
                return Jest.Expect[/* toBe */2](/* Emoji */50782054, Jest.Expect[/* expect */0](Component2$ReactTemplate.getMode(/* Emoji */50782054)));
              }));
        return Jest.test("getMode Either", (function () {
                      return Jest.Expect[/* toBe */2](true, Jest.Expect[/* expect */0](Belt_Array.every(Belt_Array.makeBy(100, (function () {
                                                return Component2$ReactTemplate.getMode(/* Either */-659631771);
                                              })), (function (x) {
                                            return x !== /* Either */-659631771;
                                          }))));
                    }));
      }));

export {
  
}
/*  Not a pure module */
