// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/bs-jest/src/jest.js";
import * as Enzyme from "bs-enzyme/src/Enzyme.js";
import * as Enzyme$1 from "enzyme";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as EnzymeAdapterReact from "enzyme-adapter-react-16";
import * as Component1$ReactTemplate from "../src/Component1.bs.js";

Enzyme.configureEnzyme(new EnzymeAdapterReact());

function setup(message) {
  return Enzyme$1.shallow(ReasonReact.element(undefined, undefined, Component1$ReactTemplate.make(message, /* array */[])));
}

function message(wrapper) {
  return wrapper.find("span").first();
}

describe("Component1", (function () {
        return Jest.test("renders message", (function () {
                      var wrapper = setup("Funky Munky");
                      return Jest.Expect[/* toBe */2]("Funky Munky", Jest.Expect[/* expect */0](wrapper.find("span").first().text()));
                    }));
      }));

export {
  setup ,
  message ,
  
}
/*  Not a pure module */
