// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Axios from "axios";
import * as Json_decode from "@glennsl/bs-json/src/Json_decode.bs.js";

function hanzi(json) {
  return /* record */[
          /* text */Json_decode.field("text", Json_decode.string, json),
          /* ordinal */Json_decode.field("ordinal", Json_decode.$$int, json)
        ];
}

function emoji(json) {
  return /* record */[
          /* shortname */Json_decode.field("shortname", Json_decode.string, json),
          /* text */Json_decode.field("text", Json_decode.string, json),
          /* category */Json_decode.field("category", Json_decode.string, json)
        ];
}

var Decode = /* module */[
  /* hanzi */hanzi,
  /* emoji */emoji
];

function getHanzi(callback) {
  Axios.get("/hanzi").then((function (res) {
            return Promise.resolve(Curry._1(callback, hanzi(res.data)));
          })).catch((function (err) {
          return Promise.resolve((console.log(err), /* () */0));
        }));
  return /* () */0;
}

function getEmoji(callback) {
  Axios.get("/emoji").then((function (res) {
            return Promise.resolve(Curry._1(callback, emoji(res.data)));
          })).catch((function (err) {
          return Promise.resolve((console.log(err), /* () */0));
        }));
  return /* () */0;
}

export {
  Decode ,
  getHanzi ,
  getEmoji ,
  
}
/* axios Not a pure module */
