// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Printf from "bs-platform/lib/es6/printf.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";

function str(prim) {
  return prim;
}

var component = ReasonReact.statelessComponent("Component1");

var counter = /* record */[/* contents */0];

function handleClick() {
  counter[0] = counter[0] + 1 | 0;
  var mesg = Curry._1(Printf.sprintf(/* Format */[
            /* String_literal */Block.__(11, [
                "You have clicked ",
                /* Int */Block.__(4, [
                    /* Int_d */0,
                    /* No_padding */0,
                    /* No_precision */0,
                    /* String_literal */Block.__(11, [
                        " times",
                        /* End_of_format */0
                      ])
                  ])
              ]),
            "You have clicked %d times"
          ]), counter[0]);
  console.log(mesg);
  return /* () */0;
}

function make(message, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", undefined, message, React.createElement("button", {
                              className: "btn btn-default btn-sm",
                              onClick: handleClick
                            }, "Click me!"));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

export {
  str ,
  component ,
  handleClick ,
  make ,
  
}
/* component Not a pure module */
